name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-dotnet-tasks:
    uses: kirandevops1993/DOTNETCORECLI-REUSABLE/.github/workflows/dotnetreusable.yml@main
    with:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration Release'

  test-dotnet-tasks:
    uses: ./.github/workflows/reusable-dotnet.yml
    with:
      command: test
      projects: '**/*Tests.csproj'
      arguments: '--configuration Release'

  pack-dotnet-tasks:
    uses: ./.github/workflows/reusable-dotnet.yml
    with:
      command: pack
      packagesToPack: '**/*.csproj'
      configuration: 'Release'

  push-dotnet-tasks:
    uses: ./.github/workflows/reusable-dotnet.yml
    with:
      command: push
      packagesToPush: './nupkgs/*.nupkg'
      publishFeedUrl: 'https://api.nuget.org/v3/index.json'
